name: card_Number_Reader
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  credit_card_scanner: null
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  syncfusion_flutter_xlsio: ^20.3.58-beta
  toast: 0.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
